version: '3.9'
volumes:
  data:
services:
  sveltekit:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5173:5173
      - 24678:24678
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    restart: always
    volumes:
      - data:/data
    ports:
      - 7878:7878